### ISSUE TITLE
alternative to socket.io

### ISSUE THREAD

**Issue by yoshuawuyts** [koajs/koa.io#1]
Last time I checked `socket.io` requires a cpp compilation step just __just to use the client__. There are many more lightweight alternatives available e.g. [sock][sock], [shoe][shoe]. What do you think of using a module other than socket.io? 

[sock]: https://github.com/sockjs/sockjs-node
[shoe]: https://github.com/substack/shoe

**Comment by oliverzy** [comment]
It's a interesting project that I think it has great potential. I think Primus (https://github.com/primus/primus) is a great candidate because it is a abstraction layer on top of other realtime framework like the ones mentioned above (socket.io, sockjs, faye-websocket, raw websocket).

This will allow people using their favorite framework.
Besides, Primus has builtin reconnection mechanism, online/offline detection, pluggable encoder/decoder and a lot of plugins.

Just my thoughts.

**Comment by bplatz** [comment]
@jonathanong Browser support for websockets isn't so much the problem as is firewall configurations that don't allow websockets traffic through, so browser support becomes secondary. That is why socket.io (or another solution that has fallback support) is still important unless you have control over the network as well as the browsers.

**Comment by jonathanong** [comment]
@bplatz that's great to know!

**Comment by clintwood** [comment]
@oliverzy +1, with abstraction offered by [Primus](https://github.com/primus/primus) would be nice to have the flexibility to switch real-time framework without breaking `koa.io`.

**Comment by llambda** [comment]
I myself would love to even just use server sent events a lot of times. However I discovered recently that many corporate firewalls and personal security software blocks not only SSE but websocket as well. :angry:  So unfortunately socket.io may be a necessity for a long time, even though websocket/SSE standalone is more pure/simpler. :sigh:

**Comment by BananaAcid** [comment]
@llambda: i agree - socket.io's fallbacks are saving me, for clients behind walls. Never know, where they are running around :) (and what restrictions apply). Using it for an API server, based on koa.io completely.

**Comment by tejasmanohar** [comment]
I vote on [ws](https://www.npmjs.com/package/ws)! It's really light-weight and clean. Primus feels too bulky/rigid/opinionated like socket.io for my taste.

**Comment by yoshuawuyts** [comment]
Fwiw after having asked this question a year ago: I'm now using [websocket-stream](https://github.com/maxogden/websocket-stream). It provides a similar interface to WebRTC, bittorrent and [other data manipulation modules](https://github.com/yoshuawuyts/knowledge/blob/master/modules.md#data-manipulation).

Since I've since found an answer to my question I'll be closing this issue. Thanks all for thinking along!

**Comment by clintwood** [comment]
@yoshuawuyts, great, have you integrated this with koa.io or are you using it standalone?  If you've integrated would be interesting to see how you did this!

**Comment by tejasmanohar** [comment]
:+1: also interested in seeing - @clintwood

**Comment by yoshuawuyts** [comment]
To be fair I've lost interest in Koa. I've found myself to much more productive using regular `http` than when relying on frameworks. [http-framework/wiki](https://github.com/Raynos/http-framework/wiki/Modules) has a good overview of which modules to use if you're ever interested in using something smaller.

Setting up a full websocket server with `http` and `websocket-stream` looks like this:

__index.js__
```js
const websocket = require('websocket-stream')
const summary = require('server-summary')
const http = require('http')

const server = http.createServer(function (req, res) {
  res.end("nope, we're testing websockets here")
})
server.listen(1337, summary(server))

const opts = { server: server }
websocket.createServer(opts, function (writeStream) {
  writeStream.end(JSON.stringify({ hello: 'world' }))
})
```

Then run the server which returns [ndjson](http://ndjson.org/) ([server-summary](https://www.npmjs.com/package/server-summary) takes care of that, can be prettified using [garnish](https://github.com/mattdesl/garnish)):
```sh
$ node .
{"name":"url","url":"http://localhost:1337","type":"connect"}
{"name":"port","message":1337}
{"name":"env","message":"undefined"}
{"name":"pid","message":20334}
```
An in another console make a request to the server using [wsnc](https://github.com/substack/wsnc) (websocket net cat):
```sh
$ wsnc http://localhost:1337
{"hello":"world"}
```

And voila, websockets without using frameworks.

**Comment by clintwood** [comment]
Wow, nice!  Thank you for coming back on this!
