### ISSUE TITLE
app.sesssion?

### ISSUE THREAD

**Issue by Xaxatix** [koajs/koa.io#11]
I haven't looked into this package too much as of yet, but because the koa-generic-session version in the example project is broken, it compelled me to go look into where it was used. And after looking it up in the application.js file, I still don't understand why it's even needed (the unfinished comment doesn't help either), so any insight would be appreciated, as I didn't find any references in the other files as well.

I'll probably answer this next question myself, after I start going over the library a bit more in-depth, but is there any way/plans for 'koa.io' and 'koa' to be decoupled and do something similar to the 'koa-router', extending the koa app object when passed in?

**Comment by gai00** [comment]
try:
app.keys = ['secret'];
app.session();

**Comment by tejasmanohar** [comment]
@gai00 works for me.
