### ISSUE TITLE
Chat demo 

### ISSUE THREAD

**Issue by bobiblazeski** [koajs/koa.io#12]
Could you please check on the demo dependencies 

1st koa-generic-session 

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\SW\\iojs\\node.exe" "D:\\SW\\iojs\\node_modules\\npm\\bin\\npm-cli.js" "i"
npm ERR! node v2.0.0
npm ERR! npm  v2.9.0
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: koa-generic-session@'>=3.0.0 <4.0.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["1.0.0","1.1.0","1.1.2","1.1.3","1.2.0","1.2.1","1.2.2","1.2.3","1.3.0","1.4.0","
1.5.0","1.6.0","1.7.0","1.8.0"]
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'socket.io-chat'
npm ERR! notarget

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Users\SlobodanB\ws\koa.io\example\chat\npm-debug.log

When I changed it to 1.8.0

D:\Users\SlobodanB\ws\koa.io\example\chat\node_modules\koa.io\node_modules\socket.io\node_modules\so
cket.io-client\node_modules\engine.io-client\node_modules\ws>if not defined npm_config_node_gyp (nod
e "D:\SW\iojs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuil
d )  else (rebuild)
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\SW\\iojs\\node.exe" "D:\\SW\\iojs\\node_modules\\npm\\bin\\npm-cli.js" "i"
npm ERR! node v2.0.0
npm ERR! npm  v2.9.0
npm ERR! file C:\Users\slobodanb\AppData\Roaming\npm-cache\debug\2.2.0\package\package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token '\u0000' at 1:1
npm ERR! 
npm ERR! ^
npm ERR! File: C:\Users\slobodanb\AppData\Roaming\npm-cache\debug\2.2.0\package\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Users\SlobodanB\ws\koa.io\example\chat\npm-debug.log

**Comment by dead-horse** [comment]
sorry. fixed

**Comment by bobiblazeski** [comment]
Thank you but I still can't install it
npm i
/


> ws@0.5.0 install D:\Users\SlobodanB\ws\koa.io\example\chat\node_modules\koa.io\node_modules\socket
.io\node_modules\engine.io\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

-
D:\Users\SlobodanB\ws\koa.io\example\chat\node_modules\koa.io\node_modules\socket.io\node_modules\en
gine.io\node_modules\ws>if not defined npm_config_node_gyp (node "D:\SW\iojs\node_modules\npm\bin\no
de-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
\


> ws@0.4.31 install D:\Users\SlobodanB\ws\koa.io\example\chat\node_modules\koa.io\node_modules\socke
t.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

|
D:\Users\SlobodanB\ws\koa.io\example\chat\node_modules\koa.io\node_modules\socket.io\node_modules\so
cket.io-client\node_modules\engine.io-client\node_modules\ws>if not defined npm_config_node_gyp (nod
e "D:\SW\iojs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuil
d )  else (rebuild)
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\SW\\iojs\\node.exe" "D:\\SW\\iojs\\node_modules\\npm\\bin\\npm-cli.js" "i"
npm ERR! node v2.0.0
npm ERR! npm  v2.9.0
npm ERR! file C:\Users\slobodanb\AppData\Roaming\npm-cache\debug\2.2.0\package\package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token '\u0000' at 1:1
npm ERR! 
npm ERR! ^
npm ERR! File: C:\Users\slobodanb\AppData\Roaming\npm-cache\debug\2.2.0\package\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Users\SlobodanB\ws\koa.io\example\chat\npm-debug.log


https://gist.github.com/bobiblazeski/a053404a43737ee15d62
