### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by ariporad** [koajs/koa.io#16]
It was last updated in May, so I thought I'd ask.

If it's not, would you be interested in having someone take it over?

**Comment by dead-horse** [comment]
I doesn't have some real projects using `koa.io` now, so if you want to take it over, i can add you as a contributor

**Comment by ariporad** [comment]
That would be awesome! I'm right now starting a project with koa.io, and would be happy to maintain it!



Thanks!Ari

**Comment by fengmk2** [comment]
:+1: @ariporad

**Comment by tunnckoCore** [comment]
@ariporad would be good to show if you can to see real usage. :)

**Comment by ariporad** [comment]
@tunnckoCore: sure. Like I said, I'm just about (ie. This afternoon), to start on a project that will use it. It will be at emiw/redstone-disbatcher, and probobly in the future at emiw/redstone-worker (not a lot of great explanation for what that is yet, sorry).

**Comment by tunnckoCore** [comment]
Okey, i'll follow them.

Btw, seeing that you use `gulp-load-plugins` and can suggest you to try 

https://github.com/jonschlinkert/load-plugins
https://github.com/tunnckoCore/load-deps lot faster than both `load-plugins` and `gulp-load-plugins`

**Comment by ariporad** [comment]
Thanks! I'll switch to load-plugins when I get home.



Thanks!Ari

**Comment by rashfael** [comment]
Nice, @ariporad!
I didn't have time for the project I did the pull requests for (#13, #14) in the last months, but I am still interested in koa.io.

**Comment by ariporad** [comment]
@rashfael: Neat! When I get push rights, I'll merge them ASAP

**Comment by ariporad** [comment]
@dead-horse: It appears that you added me to @koajs/koaio, but didn't add koajs/koa.io to it. Could you please fix that when you get a chance? Thanks!

**Comment by dead-horse** [comment]
sorry, something interrupted me at that time, done!

**Comment by ariporad** [comment]
Thanks! When I get home in a few hours I'll start working on it.




Also, I'm going to add myself as a collaborator for this repository, just so the badge isn't confusing.



Thanks!Ari

**Comment by ariporad** [comment]
@dead-horse: Thanks! I just pushed a few fixes that popped right out.

Sorry to bother you, but I was wondering if you'd consider using [semantic-release](/semantic-release/semantic-release), for future releases (if you make me a contributor on npm, I can set it up). I really like it, and use it for all my projects.

Thanks!
Ari

**Comment by ariporad** [comment]
@dead-horse: Do you think I could have npm contrib rights? Thanks!

**Comment by ariporad** [comment]
Also, I'm going to lock this, Because one I get an answer on that I'll close it.

**Comment by dead-horse** [comment]
@ariporad what's your npm user name?

**Comment by ariporad** [comment]
@dead-horse: @ariporad

**Comment by dead-horse** [comment]
added!
