### ISSUE TITLE
'add user' emit?

### ISSUE THREAD

**Issue by basickarl** [koajs/koa.io#17]
I don't see in the example how 'add user' is invoked? I was expecting a line of code to state: ```this.broadcast.emit('add user'...```

**Comment by basickarl** [comment]
Nvm found it, ```socket.emit('add user', username);``` on the client .js file. Maybe could perhaps state that the emitting can be done by both the server and client? Was slightly confusing!

**Comment by ariporad** [comment]
Yeah, because it's the client sending a message to the server. The message is sent once the user picks a username.

**Comment by basickarl** [comment]
Thank you for your quick response understand now! :)
