### ISSUE TITLE
socket.io namespace is not working.

### ISSUE THREAD

**Issue by gai00** [koajs/koa.io#29]
(forgive my english)
npm version 0.0.3:
/lib/application.js
line 83 forEach callback has no argument.

github version
/lib/application.js
line 75 same forEach callback problem.

I edit to this, worked.
namespace.forEach(function eachNamespaceUseMiddleware(ns) {
  self.io.of(ns).use(session);
});

**Comment by ariporad** [comment]
Oh yeah, that would be a problem. Thanks for reporting this! Would you like to send a PR yourself, or would you prefer that I just fix it?
