### ISSUE TITLE
Question: HTTPS?

### ISSUE THREAD

**Issue by clintwood** [koajs/koa.io#6]
It look like only HTTP is supported no HTTPS server or am I from another planet?
Edit: BTW Like what you have here!

**Comment by clintwood** [comment]
Also, wondering if I did this `https.createServer(options, app.callback()).listen(3000);` whether that would prevent the socket being attached?

**Comment by BaButtons** [comment]
I don't have an instance of koa.io in front of me right now, but were you not able to open an HTTPS connection with the secure option? i.e. `var socket = io.connect('https://localhost', {secure: true});`

**Comment by dead-horse** [comment]
```
var server = https.createServer(options, app.callback());
app.io.attach(server);
server.listen(3000);
```

didn't try this module with https, if it can't work, PR's welcome! :D

**Comment by clintwood** [comment]
Thanks will give it a try!

**Comment by clintwood** [comment]
@dead-horse, it does in fact work with https as you have it above, however, I haven't done extensive tests!

Nice!
