### ISSUE TITLE
Dependencies Express ?

### ISSUE THREAD

**Issue by Student007** [koajs/koa.io#8]
Hello Koa-Team :-)

I like your Idea of creating a new and better reboot of Express.
But I am a little bit confused about the dependency about Express 3.4.8 in the chat example ;-)

You mean "koa": ">= 0.0.3" maybe ?

**Comment by dead-horse** [comment]
sorry. it should be `"koa.io": "0.0.3".

**Comment by Student007** [comment]
oh ... fast response :-)
What about 
"dependencies":
{
"koa.io": "0.0.3",
"path": "1.x",
"fs": "x",
"koa-static-cache": "3.x"
}

**Comment by dead-horse** [comment]
fixed, thanks!
